wa_front_homepage:
    pattern:  /
    defaults: { _controller: WaFrontBundle:Home:index }

wa_add_article:
    pattern: /add
    defaults: { _controller: WaFrontBundle:Home:addArticle }

wa_test:
    pattern: /test
    defaults: { _controller: WaFrontBundle:Home:test }
    