wa_front_homepage:
    pattern:  /
    defaults: { _controller: WaFrontBundle:Home:index }

wa_front_consultation:
    pattern:  /list
    defaults: { _controller: WaFrontBundle:Home:consultation }
    
wa_front_search:
    pattern:  /search
    defaults: { _controller: WaFrontBundle:Home:search }
    



