parameters:
#    wa_front.example.class: Wa\FrontBundle\Example

services:
    wa.twig.wa_html_truncate_extension:
        class: Wa\FrontBundle\Twig\HtmlTruncate
        tags:
            - { name: twig.extension }