# app/config/routing.yml

wa_admin:
    resource: "@WaAdminBundle/Resources/config/routing.yml"
    prefix:   /admin
    
wa_member:
    resource: "@WaMemberBundle/Resources/config/routing.yml"
    prefix:   /

wa_front:
    resource: "@WaFrontBundle/Resources/config/routing.yml"
    prefix:   /
