wa_admin:
    resource: "@WaAdminBundle/Controller/"
    type:     annotation
    prefix:   /

wa_member:
    resource: "@WaMemberBundle/Controller/"
    type:     annotation
    prefix:   /

wa_front:
    resource: "@WaFrontBundle/Resources/config/routing.yml"
    prefix:   /

