<?php

namespace Wa\FrontBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArtWorkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtWorkRepository extends EntityRepository
{
}
