<?php

namespace Wa\FrontBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * IdeaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IdeaRepository extends EntityRepository {

    public function getTodayTopIdea() {
        //http://stackoverflow.com/questions/12893006/symfony2-doctrine-order-entites-by-foreign-attribute
        //$query = $this->_em->createQuery('SELECT i FROM WaFrontBundle:Idea i JOIN i.votes v WHERE v.date = date(today)');
        //$resultats = $query->getResult();

        //return $resultats;
        return null;
    }
    
    public function getWeekTopIdea() {
        //http://stackoverflow.com/questions/12893006/symfony2-doctrine-order-entites-by-foreign-attribute
        //$query = $this->_em->createQuery('SELECT i FROM WaFrontBundle:Idea i JOIN i.votes v WHERE v.date = date(today)');
        //$resultats = $query->getResult();

        //return $resultats;
        return null;
    }

}
