<?php

namespace Wa\FrontBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository {

    public function findAutocompleteTitles($title, $limit = 10) {
        $qb = $this->createQueryBuilder('t');
        $qb->select('t')
                ->where('t.title LIKE :title')
                ->setParameter('term', '%' . $title . '%')
                ->setMaxResults($limit);

        $arrayAss = $qb->getQuery()
                ->getArrayResult();
        
        // Transformer le tableau associatif en un tableau standard
	$array = array();
	foreach($arrayAss as $title)
	{
		$array[] = $title->getTitle();
	}
 
	return $array;
    }

}
