<?php

namespace Wa\FrontBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ThemeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThemeRepository extends EntityRepository {

    public function getIndexThemes() {
        // current week number :
        $date = new \DateTime();  // today
        $week = (int) $date->format("W");
        
        // select theme from previous, current and next week :
        $qb = $this->createQueryBuilder('t');
        $qb->where('t.week >= :weekMoins')
                ->setParameter('weekMoins', $week - 1)
                ->andWhere('t.week <= :weekPlus')
                ->setParameter('weekPlus', $week + 1)
                ->orderBy('t.week', 'ASC');

        return $qb->getQuery()->getResult();
    }
    
    public function getCurrentTheme() {
        // current week number :
        $date = new \DateTime();  // today
        $week = (int) $date->format("W");
        // select week's theme
        return $this->findOneByWeek($week);
    }

}
